# Generated by Django 4.2.11 on 2025-11-17 18:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                    )
                 ),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(
                    fields=['sent', 'created_at'],
                    name='outbox_outb_sent_4993d6_idx'
                )
                ],
            },
        ),
    ]
