# Generated by Django 4.2.11 on 2025-11-17 18:54

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(
                verbose_name=(
                    'дата проведения                                       '
                    'мероприятия'
                )
            ),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)
                 ),
                ('full_name', models.CharField(
                    max_length=128,
                    validators=[django.core.validators.MaxLengthValidator(128)]
                    )
                 ),
                ('email', models.EmailField(
                    max_length=254,
                    validators=[django.core.validators.EmailValidator()]
                    )
                 ),
                ('confirmation_code', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='registrations',
                    to='events.event'
                 )
                 ),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
